// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVg4oE2RORT7IRBPCNXFDtEIq_9PPQjE8',
    appId: '1:421596843468:web:ca5d73816f518c3936a169',
    messagingSenderId: '421596843468',
    projectId: 'lastchance-ec0df',
    authDomain: 'lastchance-ec0df.firebaseapp.com',
    storageBucket: 'lastchance-ec0df.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnwgtJbOj-MqdRWHiUASO4msM6c6VfT3A',
    appId: '1:421596843468:android:bd1905e7a757c35936a169',
    messagingSenderId: '421596843468',
    projectId: 'lastchance-ec0df',
    storageBucket: 'lastchance-ec0df.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzmXtp8nmTQNmTZ3lvwH_504dP-azoFNw',
    appId: '1:421596843468:ios:c3c29474a981526e36a169',
    messagingSenderId: '421596843468',
    projectId: 'lastchance-ec0df',
    storageBucket: 'lastchance-ec0df.appspot.com',
    iosBundleId: 'com.example.assignment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzmXtp8nmTQNmTZ3lvwH_504dP-azoFNw',
    appId: '1:421596843468:ios:a1060bac631dae3936a169',
    messagingSenderId: '421596843468',
    projectId: 'lastchance-ec0df',
    storageBucket: 'lastchance-ec0df.appspot.com',
    iosBundleId: 'com.example.assignment.RunnerTests',
  );
}
